/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AnimalInsert.java
 *
 * Created on 29-Apr-2014, 20:24:08
 */

package CombinedProjectPackage;
//import JavaImageResizer.resize;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import inheritance_folder.Animal;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
//import org.jdesktop.swingx.JDatePicker;

/**
 *
 * @author MF-Laptop
 */
public class AnimalInsert extends javax.swing.JFrame {

    private PreparedStatement prest;

    /** Creates new form AnimalInsert */
    public AnimalInsert() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jSpinner1 = new javax.swing.JSpinner();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        AnimalID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Space = new javax.swing.JTextField();
        AnimalName = new javax.swing.JTextField();
        Diet = new javax.swing.JTextField();
        OK = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        AnimalType = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        Diet_Type = new javax.swing.JComboBox();
        StatusList = new javax.swing.JComboBox();
        HealthStatus = new javax.swing.JComboBox();
        picker = new org.jdesktop.swingx.JXDatePicker();
        Complete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Animal ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 90, 14);

        AnimalID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalIDActionPerformed(evt);
            }
        });
        getContentPane().add(AnimalID);
        AnimalID.setBounds(110, 10, 100, 20);

        jLabel2.setText("Animal Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 100, 14);

        jLabel3.setText("Type");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 70, 100, 14);

        jLabel4.setText("Gender");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 100, 100, 14);

        jLabel5.setText("DOB");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 130, 100, 14);

        jLabel6.setText("Status");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 220, 60, 14);

        jLabel8.setText("Diet");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 190, 70, 20);

        jLabel10.setText("Diet type");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 160, 70, 14);

        jLabel9.setText("Health");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 250, 70, 20);

        jLabel11.setText("Req Space");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 280, 80, 20);
        getContentPane().add(Space);
        Space.setBounds(110, 280, 110, 20);
        getContentPane().add(AnimalName);
        AnimalName.setBounds(110, 40, 100, 20);
        getContentPane().add(Diet);
        Diet.setBounds(110, 190, 100, 20);

        OK.setText("Insert image");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK);
        OK.setBounds(20, 310, 200, 23);

        jButton1.setText("Main menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 370, 200, 20);

        AnimalType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mammal", "Amphibian", "Bird", "Reptile","Invertebrate" }));
        AnimalType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalTypeActionPerformed(evt);
            }
        });
        getContentPane().add(AnimalType);
        AnimalType.setBounds(110, 70, 100, 20);

        buttonGroup5.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(100, 100, 60, 23);

        buttonGroup5.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(160, 100, 110, 20);

        Diet_Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Herbivore", "Carnivore", "Frugivore","Insectivore","Omnivore"}));
        Diet_Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diet_TypeActionPerformed(evt);
            }
        });
        getContentPane().add(Diet_Type);
        Diet_Type.setBounds(110, 160, 100, 20);

        StatusList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Good", "Threatened", "Endangered","Critically Endangered"}));
        StatusList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusListActionPerformed(evt);
            }
        });
        getContentPane().add(StatusList);
        StatusList.setBounds(110, 220, 100, 20);

        HealthStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Good", "Healthy", "Unwell"}));
        HealthStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HealthStatusActionPerformed(evt);
            }
        });
        getContentPane().add(HealthStatus);
        HealthStatus.setBounds(110, 250, 100, 20);

        picker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickerActionPerformed(evt);
            }
        });
        getContentPane().add(picker);
        picker.setBounds(110, 130, 100, 22);

        Complete.setText("Insertion Complete!");
        Complete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompleteActionPerformed(evt);
            }
        });
        getContentPane().add(Complete);
        Complete.setBounds(20, 340, 200, 23);

        setSize(new java.awt.Dimension(341, 457));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AnimalIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimalIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnimalIDActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        
        String url = "jdbc:mysql://localhost:3306/";
String dbName = "zoodb";
String driver = "com.mysql.jdbc.Driver";
String userName = "root";
String password = "abhiram";

//String a[]={""};
           

        try{
        Animal A = new Animal();
       //String s=(String) ;
        //System.out.println(s+" hello");
        A.setAnimal_ID(AnimalID.getText());
        A.setAnimal_Name(AnimalName.getText());
        A.setAnimal_Type((String)AnimalType.getSelectedItem()); //mammal, birds, reptile, amphibian, invertebrate
        A.setGender((String)getSelectedButtonText(buttonGroup5));
        //JXDatePicker picker;
          //  picker = new JXDatePicker();
        picker.setDate(Calendar.getInstance().getTime());
        picker.setFormats(new SimpleDateFormat("dd-MM-yyyy"));
        DateFormat fomt= new SimpleDateFormat("yyyy-MM-dd");
        A.setDOB(fomt.format(picker.getDate())); 
        //A.setDOB(picker.getDate());
        System.out.println(picker.getDate()+"test");//insert Calender
        A.setDiet_Type((String)Diet_Type.getSelectedItem());  //herbivore, carnivore, omnivore, insectivore, fruitthing
        A.setDiet(Diet.getText());  
        A.setStatus((String)StatusList.getSelectedItem()); //good, endangered, threatened, critically endangered, 
        A.setHealth((String)HealthStatus.getSelectedItem()); //good, healthy, unwell
        A.setSpace_Required_Acres(Integer.parseInt(Space.getText()));

        Class.forName(driver).newInstance();
        System.out.println("Connection to database" + dbName + "...");
        Connection conn = (Connection) DriverManager.getConnection(url+dbName,userName,password);
        System.out.println("Connected database succesfully...");

        String sql = "INSERT INTO animal (ANIMAL_ID,ANIMAL_NAME,ANIMAL_TYPE,GENDER," +
                "DOB,DIET_TYPE,DIET,STATUS,HEALTH,SPACE_REQUIRED_ACRES)" +
                "VALUES(?,?,?,?,?,?,?,?,?,?)";

        prest = conn.prepareStatement(sql);

        prest.setString(1, A.getAnimal_ID());
        prest.setString(2, A.getAnimal_Name());
        prest.setString(3, A.getAnimal_Type());
        prest.setString(4, A.getGender());
        prest.setString(5, A.getDOB());
        prest.setString(6, A.getDiet_Type());
        prest.setString(7, A.getDiet());
        prest.setString(8, A.getStatus());
        prest.setString(9, A.getHealth());
        prest.setInt(10, A.getSpace_Required_Acres());
        
        prest.execute();
        callAll(A.getAnimal_ID());
        conn.close();
        
        }catch (Exception e){
        e.printStackTrace();
        }
        
        


    }//GEN-LAST:event_OKActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ManagerFrame Frame1= new ManagerFrame ();
        Frame1.setVisible(true);

        setVisible(false);//this line and the one below close the login form.
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null; 
    }
    
    
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void AnimalTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimalTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnimalTypeActionPerformed

    private void Diet_TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Diet_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Diet_TypeActionPerformed

    private void StatusListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusListActionPerformed

    private void HealthStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HealthStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HealthStatusActionPerformed

    private void pickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pickerActionPerformed

    private void CompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompleteActionPerformed
        ManagerFrame Frame1= new ManagerFrame ();
        Frame1.setVisible(true);

        setVisible(false);//this line and the one below close the login form.
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_CompleteActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimalInsert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnimalID;
    private javax.swing.JTextField AnimalName;
    private javax.swing.JComboBox<String> AnimalType;
    private javax.swing.JButton Complete;
    private javax.swing.JTextField Diet;
    private javax.swing.JComboBox<String> Diet_Type;
    private javax.swing.JComboBox<String> HealthStatus;
    private javax.swing.JButton OK;
    private javax.swing.JTextField Space;
    private javax.swing.JComboBox<String> StatusList;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSpinner jSpinner1;
    private org.jdesktop.swingx.JXDatePicker picker;
    // End of variables declaration//GEN-END:variables

     JFrame f;
    JButton btn, btn2;
    ImageShow panel;
    public void callAll(final String s) throws IOException {
        f = new JFrame("Image Load");
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        btn = new JButton("Select Image to Load");
        btn2 =new JButton("Return to Insertion");
        
        btn2.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e) {
            f.dispatchEvent(new WindowEvent(f, WindowEvent.WINDOW_CLOSING));
        }});
        btn.addActionListener(new ActionListener() {
 
            public void actionPerformed(ActionEvent e) {
 
                JFileChooser fc = new JFileChooser("..\\..\\..\\..\\ZooWebpage\\static\\images\\animals\\");
                fc.showOpenDialog(f);
 
                try {
                    panel = new ImageShow(fc.getSelectedFile().getPath(),s);
                } catch (IOException ex) {
                    System.out.println("Error");
                }
 
                f.add(panel, BorderLayout.CENTER);
                f.setLocation(200, 200);
                f.setSize(panel.width+50, panel.height+75);
                btn.setVisible(false);
                f.add(btn2,BorderLayout.SOUTH);
 
            }
        });
 
        f.add(btn, BorderLayout.CENTER);
        f.pack();
        f.setSize(new java.awt.Dimension(300, 200));
        f.setLocation(400, 400);
        f.setVisible(true);
        
 
    }
}

class ImageShow extends JPanel {
 
    private String path;
    private Image img;
    public int width, height;
 
    public ImageShow(String path,String s) throws IOException {
 
        this.path = path;
        img = ImageIO.read(new File(path));
        
        width = img.getWidth(this);
        height = img.getHeight(this) + 38;
        //154
        //116
      System.out.println(img.getWidth(this));
      System.out.println(img.getHeight(this));
        String location = "..\\..\\..\\..\\ZooWebpage\\static\\images\\animals\\"+s+".jpg"; 
        String format = "jpg"; // "PNG" for example
        
        ImageIO.write((BufferedImage) img, format, new File(location));
    }

    ImageShow() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
 
    @Override
    public void paint(Graphics g) {
        if (img != null) {
            g.drawImage(img, 15, 22, this);
        }
    }
}
