/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Query.java
 *
 * Created on 04-May-2014, 00:48:09
 */

package CombinedProjectPackage;

import inheritance_folder.Animal;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.ComboBoxModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author MF-Laptop
 */
public class Query extends javax.swing.JFrame {

    private PreparedStatement prest;
    Animal A = new Animal();

    /** Creates new form Query */
    public Query() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Output = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        Sample = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Submit Query");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 40, 140, 23);

        Output.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Output);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 590, 160);

        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(500, 80, 80, 23);

        Sample.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SampleMouseClicked(evt);
            }
        });
        Sample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SampleActionPerformed(evt);
            }
        });
        getContentPane().add(Sample);
        Sample.setBounds(30, 40, 400, 50);

        jLabel1.setText("Input Query to be Executed ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 14, 280, 20);

        setSize(new java.awt.Dimension(644, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

          String url = "jdbc:mysql://localhost:3306/";
String dbName = "zoodb";
String driver = "com.mysql.jdbc.Driver";
String userName = "root";
String password = "";


        try
        {
                Class.forName(driver).newInstance();
                Connection conn = (Connection) DriverManager.getConnection(url + dbName, userName, password);
                System.out.println("Database Connection Successful");

                // Set Up SQL
                //String sql = "SELECT * FROM animal LIKE ?";
                String sql = Sample.getText();
                System.out.println("Input Query: "+sql);
                // Excute Query and send result set to rs
                prest = (PreparedStatement) conn.prepareStatement(sql);
                
                ResultSet rs = prest.executeQuery();

                //Retrieve by column name
                Output.setModel(DbUtils.resultSetToTableModel(rs));

                rs.close();
                prest.close();

                // Close the connection to the database
                conn.close();

          }
                catch (Exception e)
                {
                e.printStackTrace();
                
       
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ManagerFrame Frame1= new ManagerFrame ();
        Frame1.setVisible(true);

        setVisible(false);//this line and the one below close the login form.
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SampleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SampleActionPerformed

    private void SampleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SampleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SampleMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Query().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Output;
    private javax.swing.JTextField Sample;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
